// frontend/src/app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '../contexts/AuthContext'; // Adjust path

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My Scaffold App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {/* You might want a main layout component here for Nav/Footer */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}