# Generated by Django 5.2.4 on 2025-07-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text="The date and time when the user's email was verified.", null=True, verbose_name='email verified at'),
        ),
    ]
